teamspeak3server:
  container_name: teamspeak3server
  hostname: teamspeak3server
  image: a1exei/teamspeak3-server
  ports:
    - "9987:9987/udp"
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./data:/data
  restart: always
